services:
    nestjs_api:
      build: 
        context: .
        dockerfile: dockerfile
      ports:
        - "4000:4000"
      secrets:
        - AI_TOOL_KEY
      environment:
        - AI_TOOL_KEY=/run/secrets/AI_TOOL_KEY
        - PORT=4000
        - NODE_ENV=production
      networks:
        - caddy-shared

networks:
  caddy-shared:
    external: true

secrets:
  AI_TOOL_KEY:
    external: true