version: "3.8"

services:
  web:
    image: ghcr.io/trigael/ai-logo-generator:${GIT_COMMIT_HASH}

    # PROD: 4001/4002, STAGING: 4000
    ports:
      - "${EXPOSE_PORT}:4000"

    networks:
      - ai-logo-caddy
      - caddy-shared-swarm
      - app-net

    # Graceful shutdown 
    stop_grace_period: 60s
    
    secrets:
      - OPENAI_API_KEY_${SHORT_SHA_SAFE}
      - FRONTEND_URL_${SHORT_SHA_SAFE}
      - BACKEND_URL_${SHORT_SHA_SAFE}
      # STRIPE
      - STRIPE_PUBLISHABLE_KEY_${SHORT_SHA_SAFE}
      - STRIPE_SECRET_KEY_${SHORT_SHA_SAFE}
      - STRIPE_WEBHOOK_KEY_${SHORT_SHA_SAFE}
      # Mailjet
      - MAILJET_API_KEY_${SHORT_SHA_SAFE}
      - MAILJET_API_SECRET_${SHORT_SHA_SAFE}
      - MAILJET_FROM_EMAIL_${SHORT_SHA_SAFE}
      - MAILJET_TEMPLATE_ID_${SHORT_SHA_SAFE}
      # SENTRY
      - SENTRY_DSN_${SHORT_SHA_SAFE}
      # Grafana Loki
      - LOKI_USERNAME_${SHORT_SHA_SAFE}
      - LOKI_PASSWORD_${SHORT_SHA_SAFE}
      # DB = SUPABASE
      - DB_TRANSACTION_URL_${SHORT_SHA_SAFE}
      # Hugging Face
      - HF_API_KEY_${SHORT_SHA_SAFE}
      # Black Forest
      - BLACK_FOREST_API_KEY_${SHORT_SHA_SAFE}
      # Hetzner
      - HETZNER_SECRET_KEY_${SHORT_SHA_SAFE}
      - HETZNER_ACCESS_KEY_${SHORT_SHA_SAFE}

    environment:
      - PORT=4000
      - NODE_ENV=${ENV_KEY}
      - GIT_COMMIT_HASH=${GIT_COMMIT_HASH}
      - OPENAI_API_KEY=/run/secrets/OPENAI_API_KEY_${SHORT_SHA_SAFE}
      - FRONTEND_URL=/run/secrets/FRONTEND_URL_${SHORT_SHA_SAFE}
      - BACKEND_URL=/run/secrets/BACKEND_URL_${SHORT_SHA_SAFE}
      - REDIS_URL=${REDIS_URL_KEY}
      # STRIPE
      - STRIPE_PUBLISHABLE_KEY=/run/secrets/STRIPE_PUBLISHABLE_KEY_${SHORT_SHA_SAFE}
      - STRIPE_SECRET_KEY=/run/secrets/STRIPE_SECRET_KEY_${SHORT_SHA_SAFE}
      - STRIPE_WEBHOOK_KEY=/run/secrets/STRIPE_WEBHOOK_KEY_${SHORT_SHA_SAFE}
      # Mailjet
      - MAILJET_API_KEY=/run/secrets/MAILJET_API_KEY_${SHORT_SHA_SAFE}
      - MAILJET_API_SECRET=/run/secrets/MAILJET_API_SECRET_${SHORT_SHA_SAFE}
      - MAILJET_FROM_EMAIL=/run/secrets/MAILJET_FROM_EMAIL_${SHORT_SHA_SAFE}
      - MAILJET_FROM_NAME=AI LOGO GENERATOR
      - MAILJET_TEMPLATE_ID=/run/secrets/MAILJET_TEMPLATE_ID_${SHORT_SHA_SAFE}
      # Sentry
      - SENTRY_DSN=/run/secrets/SENTRY_DSN_${SHORT_SHA_SAFE}
      # Grafana Loki
      - LOKI_USERNAME=/run/secrets/LOKI_USERNAME_${SHORT_SHA_SAFE}
      - LOKI_PASSWORD=/run/secrets/LOKI_PASSWORD_${SHORT_SHA_SAFE}
      # DB = SUPABASE
      - DB_TRANSACTION_URL=${DB_URL_KEY}
      # Hugging Face
      - HF_API_KEY=/run/secrets/HF_API_KEY_${SHORT_SHA_SAFE}
      # Black Forest
      - BLACK_FOREST_API_KEY=/run/secrets/BLACK_FOREST_API_KEY_${SHORT_SHA_SAFE}
      # Hetzner
      - HETZNER_SECRET_KEY=/run/secrets/HETZNER_SECRET_KEY_${SHORT_SHA_SAFE}
      - HETZNER_ACCESS_KEY=/run/secrets/HETZNER_ACCESS_KEY_${SHORT_SHA_SAFE}

    deploy:
      replicas: 2
      update_config:
        order: start-first
        parallelism: 1
        failure_action: rollback
      restart_policy:
        condition: on-failure
      labels:
        - redeploy-trigger=${GIT_COMMIT_HASH}

    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:4000/health || exit 1"]
      interval: 10s
      timeout: 2s
      retries: 6
      start_period: 10s

networks:
  ai-logo-caddy:
    external: true
  caddy-shared-swarm:
    external: true
  app-net:
    external: true

secrets:
  OPENAI_API_KEY_${SHORT_SHA_SAFE}: { external: true }
  FRONTEND_URL_${SHORT_SHA_SAFE}: { external: true }
  BACKEND_URL_${SHORT_SHA_SAFE}: { external: true }
  STRIPE_PUBLISHABLE_KEY_${SHORT_SHA_SAFE}: { external: true }
  STRIPE_SECRET_KEY_${SHORT_SHA_SAFE}: { external: true }
  STRIPE_WEBHOOK_KEY_${SHORT_SHA_SAFE}: { external: true }
  MAILJET_API_KEY_${SHORT_SHA_SAFE}: { external: true }
  MAILJET_API_SECRET_${SHORT_SHA_SAFE}: { external: true }
  MAILJET_FROM_EMAIL_${SHORT_SHA_SAFE}: { external: true }
  MAILJET_TEMPLATE_ID_${SHORT_SHA_SAFE}: { external: true }
  SENTRY_DSN_${SHORT_SHA_SAFE}: { external: true }
  LOKI_USERNAME_${SHORT_SHA_SAFE}: { external: true }
  LOKI_PASSWORD_${SHORT_SHA_SAFE}: { external: true }
  DB_TRANSACTION_URL_${SHORT_SHA_SAFE}: { external: true }
  HF_API_KEY_${SHORT_SHA_SAFE}: { external: true }
  BLACK_FOREST_API_KEY_${SHORT_SHA_SAFE}: { external: true }
  HETZNER_SECRET_KEY_${SHORT_SHA_SAFE}: { external: true }
  HETZNER_ACCESS_KEY_${SHORT_SHA_SAFE}: { external: true }
