services:
    nestjs_api:
      build: 
        context: .
        dockerfile: dockerfile
      ports:
        - "4000:4000"
      secrets:
        - LOGO_GENERATOR_TOOL_API_KEY
      environment:
        - LOGO_GENERATOR_TOOL_API_KEY=/run/secrets/LOGO_GENERATOR_TOOL_API_KEY
        - PORT=4000
        - NODE_ENV=production
      networks:
        - caddy-shared

networks:
  caddy-shared:
    external: true

secrets:
  LOGO_GENERATOR_TOOL_API_KEY:
    external: true