services:
    nestjs_api:
      build: 
        context: .
        dockerfile: dockerfile
      ports:
        - "4000:4000"
      environment:
        - LOGO_GENERATOR_TOOL_API_KEY=${LOGO_GENERATOR_TOOL_API_KEY}
        - PORT=4000
        - NODE_ENV=production
      networks
        - caddy-shared

networks:
  caddy-shared:
    external: true